# generated by Sonnet 4.6
# tests/test_block_manager.py
import pytest
from sequence import Sequence, SequenceGroup, SequenceStatus
from block_manager import BlockSpaceManager, PhysicalBlock

BLOCK_SIZE = 4
NUM_BLOCKS = 16


def make_seq(seq_id: int, prompt_len: int, block_size: int = BLOCK_SIZE) -> Sequence:
    return Sequence(seq_id, list(range(prompt_len)), block_size)


def make_group(seq_id: int, prompt_len: int) -> SequenceGroup:
    seq = make_seq(seq_id, prompt_len)
    return SequenceGroup(request_id=f"req-{seq_id}", seqs=[seq])


# ------------------------------------------------------------------ #
# 1. Basic allocate / free                                           #
# ------------------------------------------------------------------ #

class TestAllocateFree:
    def test_allocate_consumes_blocks(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        group = make_group(0, prompt_len=7)   # 7 tokens → ceil(7/4)=2 blocks
        assert bsm.can_allocate(group)
        bsm.allocate(group)
        assert bsm.num_free_blocks == NUM_BLOCKS - 2

    def test_free_returns_blocks(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        group = make_group(0, prompt_len=7)
        bsm.allocate(group)
        seq = group.get_seqs()[0]
        bsm.free(seq)
        assert bsm.num_free_blocks == NUM_BLOCKS

    def test_status_becomes_running_after_allocate(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        group = make_group(0, prompt_len=4)
        bsm.allocate(group)
        assert group.get_seqs()[0].status == SequenceStatus.RUNNING

    def test_block_table_length_matches_logical_blocks(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        for prompt_len in [1, 4, 5, 8, 9]:
            group = make_group(prompt_len, prompt_len)
            bsm.allocate(group)
            seq = group.get_seqs()[0]
            assert len(bsm.get_block_table(seq)) == seq.num_logic_blocks
            bsm.free(seq)


# ------------------------------------------------------------------ #
# 2. OOM detection                                                   #
# ------------------------------------------------------------------ #

class TestOOM:
    def test_can_allocate_false_when_not_enough_blocks(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, num_gpu_blocks=2)
        group = make_group(0, prompt_len=9)  # requires 3 blocks
        assert not bsm.can_allocate(group)

    def test_allocate_raises_on_oom(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, num_gpu_blocks=1)
        group = make_group(0, prompt_len=9)
        with pytest.raises(MemoryError):
            bsm.allocate(group)  # can_allocate returns False; forcing allocate should raise

    def test_can_append_slot_false_when_full(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, num_gpu_blocks=2)
        group = make_group(0, prompt_len=8)  # exactly 2 blocks used
        bsm.allocate(group)
        assert bsm.num_free_blocks == 0
        assert not bsm.can_append_slot(group)


# ------------------------------------------------------------------ #
# 3. append_slot: block expansion during decode                      #
# ------------------------------------------------------------------ #

class TestAppendSlot:
    def test_no_new_block_needed_within_existing_block(self):
        """prompt=5 tokens → 2 blocks; the 6th token still fits inside the 2nd block"""
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        group = make_group(0, prompt_len=5)
        bsm.allocate(group)
        seq = group.get_seqs()[0]
        free_before = bsm.num_free_blocks

        seq.append_token_id(999)
        cow = bsm.append_slot(seq)

        assert cow is None
        assert bsm.num_free_blocks == free_before  # no new block allocated

    def test_new_block_allocated_when_block_full(self):
        """prompt=8 tokens → 2 full blocks; decoding the 9th token requires a new block"""
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        group = make_group(0, prompt_len=8)
        bsm.allocate(group)
        seq = group.get_seqs()[0]
        free_before = bsm.num_free_blocks

        seq.append_token_id(999)
        cow = bsm.append_slot(seq)

        assert cow is None
        assert bsm.num_free_blocks == free_before - 1
        assert len(bsm.get_block_table(seq)) == 3

    def test_multiple_decode_steps(self):
        """Decode 12 steps consecutively; blocks expand on demand"""
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        group = make_group(0, prompt_len=3)
        bsm.allocate(group)
        seq = group.get_seqs()[0]

        for i in range(12):
            seq.append_token_id(i)
            bsm.append_slot(seq)

        # 3+12=15 tokens → ceil(15/4)=4 blocks
        assert len(bsm.get_block_table(seq)) == 4


# ------------------------------------------------------------------ #
# 4. fork + Copy-on-Write                                             #
# ------------------------------------------------------------------ #

class TestForkAndCoW:
    def test_fork_shares_blocks(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        group = make_group(0, prompt_len=8)
        bsm.allocate(group)
        parent = group.get_seqs()[0]

        child = make_seq(seq_id=1, prompt_len=8)
        child.status = SequenceStatus.RUNNING
        free_before = bsm.num_free_blocks

        bsm.fork(parent, child)

        # fork does not consume additional physical blocks
        assert bsm.num_free_blocks == free_before
        # block_table entries point to the same physical block objects (shared)
        assert bsm.get_block_table(parent) == bsm.get_block_table(child)

    def test_cow_triggers_on_shared_write(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        # last block has 1 token and 3 empty slots; decode will not allocate a new block
        group = make_group(0, prompt_len=5)
        bsm.allocate(group)
        parent = group.get_seqs()[0]

        child = make_seq(seq_id=1, prompt_len=5)
        child.status = SequenceStatus.RUNNING
        bsm.fork(parent, child)

        free_before = bsm.num_free_blocks

        # parent decodes one step → last block ref_count=2 → CoW triggered
        parent.append_token_id(100)
        cow = bsm.append_slot(parent)

        assert cow is not None                  # CoW was triggered
        old_num, new_num = cow
        assert old_num != new_num
        assert bsm.num_free_blocks == free_before - 1  # one extra block allocated

        # child block_table still points to the old block
        child_table = bsm.get_block_table(child)
        parent_table = bsm.get_block_table(parent)
        assert child_table[-1] == old_num
        assert parent_table[-1] == new_num

    def test_free_after_fork_decrements_refcount(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        group = make_group(0, prompt_len=4)
        bsm.allocate(group)
        parent = group.get_seqs()[0]

        child = make_seq(seq_id=1, prompt_len=4)
        child.status = SequenceStatus.RUNNING
        bsm.fork(parent, child)

        # free parent: shared block ref_count drops from 2 to 1; should not return to pool yet
        bsm.free(parent)
        free_after_parent_free = bsm.num_free_blocks

        # free child: ref_count reaches 0; block is now returned to pool
        bsm.free(child)
        assert bsm.num_free_blocks == free_after_parent_free + 1


# ------------------------------------------------------------------ #
# 5. Full lifecycle                                                   #
# ------------------------------------------------------------------ #

class TestFullLifecycle:
    def test_allocate_decode_free_restores_pool(self):
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        initial_free = bsm.num_free_blocks

        group = make_group(0, prompt_len=6)
        bsm.allocate(group)
        seq = group.get_seqs()[0]

        for i in range(20):
            seq.append_token_id(i)
            bsm.append_slot(seq)

        bsm.free(seq)
        assert bsm.num_free_blocks == initial_free   # all blocks fully returned

    def test_block_table_values_are_valid_indices(self):
        """Physical block indices must be within valid range; an out-of-bounds index passed to the kernel will cause undefined behaviour."""
        bsm = BlockSpaceManager(BLOCK_SIZE, NUM_BLOCKS)
        group = make_group(0, prompt_len=3)
        bsm.allocate(group)
        seq = group.get_seqs()[0]

        for i in range(10):
            seq.append_token_id(i)
            bsm.append_slot(seq)

        table = bsm.get_block_table(seq)
        for idx in table:
            assert 0 <= idx < NUM_BLOCKS